export const plan = [
  {
    label: 'free trail',
    benefits: [
      'browsing plugin (20 massage)',
      'diagram plugin 20 diagram & mind map)',
      'chat with pdf  including : (ocr & upload multiple pdf files)',
      'summariztion ',
      'question& answer generator (25 Q&A)',
    ],
  },
  {
    label: 'basic',
    price: 99,
    benefits: [
      'browsing plugin (100massage)',
      'daigram plugin unlimited',
      'chat with pdf',
      'summariztion',
      'question and answer generator ( 170 Q&A)',
      '  document ocr ai',
    ],
  },
  {
    label: 'standard',
    price: 149,
    benefits: [
      'GPT Prof ( including explanition & discussion)',
      'browsing plugin (200 massage)',
      'daigram plugin (unlimited)',
      'chat with pdf (unlimited)',
      'summariztion ( unlimited)',
      'question and answer generator (300 Q&A)',
      'document ocr ai',
      'audio transcribtion & summariztion (soon)',
      'video transcribtion & summariztion (soon)',
      'youtube video transcribtion & summariztion (soon)',
    ],
  },
  {
    label: 'premium',
    price: 299,
    benefits: [
      'GPT prof ( including explanition & discussion)',
      'browsing plugin (unlimited)',
      'diagram plugin (unlimited)',
      'hat with pdf (unlimited)',
      'summariztion (unlimited ) ',
      'question & answer generator ( unlimited)',
      'document ocr ai (unlimited)',
      'audio transcribtion & summariztion (soon)',
      'video transcribtion & summariztion (soon)',
      'outube video transcribtion & summariztion (soon)',
    ],
  },
  {
    label: 'premium',
    price: 2999,
    benefits: [
      'GPT prof ( including explanition & discussion) ',
      'browsing plugin (unlimited)',
      'diagram plugin (unlimited)',
      'hat with pdf (unlimited)',
      'AI Summaries & Notes (unlimited )  ',
      'question & answer generator ( unlimited)',
      'document ocr ai (unlimited)',
      'audio transcribtion & summariztion (unlimited)',
      'video transcribtion & summariztion (unlimited)',
      'youtube video transcribtion & summariztion (unlimited)',
    ],
  },
];
