export const colors = {
  default: {
    background: '#07091e',
    foreground: '#ffffff',
    glow: '#3A1078',
    card: '#ffffff',
    'card-foreground': '#000000',
    popover: '#2CB49F',
    'popover-foreground': '#000000',
    primary: '#2CB49F',
    'primary-light': '#39F29B',
    'primary-foreground': '#f7f9fc',
    secondary: '#f7f7f7',
    'secondary-foreground': '#0e0e0e',
    muted: '#ACFFAD',
    'muted-foreground': '#d6d9df',
    accent: '#652abb',
    'accent-foreground': '#0e0e0e',
    destructive: '#f95757',
    'destructive-foreground': '#fafafa',
    border: '#e4e4e4',
    input: '#e4e4e4',
    ring: '#ff6767',
  },
};
